name: Build and deploy

on:
    push:
        branches: ["main"]

jobs:
    build:
        name: Build and deploy
        runs-on: ubuntu-latest

        steps:
            - name: Get files
              uses: actions/checkout@v5

            - name: Setup Node.js
              uses: actions/setup-node@v5
              with:
                  node-version: 24
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Build project
              run: npm run build

            - name: Output commit hash
              run: |
                  SHORT_HASH=$(echo "${GITHUB_SHA::7}")
                  sed -i "s/{{COMMIT_HASH}}/$SHORT_HASH/g" dist/index.html dist/admin/index.html

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: build-dist
                  path: ./dist/

    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Download build artifacts
              uses: actions/download-artifact@v5
              with:
                  name: build-dist
                  path: ./

            - name: Web deploy
              uses: SamKirkland/web-deploy@v1
              with:
                  target-server: ${{ secrets.TARGET_SERVER }}
                  remote-user: ${{ secrets.REMOTE_USER }}
                  private-ssh-key: ${{ secrets.SSH_KEY }}
                  source-path: ./
                  destination-path: ${{ secrets.DESTINATION_PATH }}
                  rsync-options:
                      --archive --verbose --compress --human-readable --progress --delete-after
                      --exclude=.git/ --exclude=.htaccess --exclude=.htpasswd
                      --exclude=config.json --exclude=news/
